### ISSUE TITLE
 Autocompletion for names

### ISSUE THREAD

**Issue by trowik** [adfinis/timed#71]
Everyone in Projects and Support needs to refer to colleagues several times a day. To reduce typos and make it more convenient not to use nicknames I would suggest some kind of autocompletion. Similar to how it works in Redmine.

@nickname = Full Name

Or maybe without prefix.

**Comment by Jana90JL** [comment]
**To be defined:** How should the name be displayed? Full & Lastname?

**Comment by c0rydoras** [comment]
There is still:
- [x] filtering out archived/inactive users && invalid users (that can't be completed, or make no sense to be completed) #1446 
- [x] quirks when using this inside of the magic link modal (it resizes it, for some reason) #1448
- [x] using this in on the analysis page (the filter sidebar), which is non-trivial due to z-index stuff 🙃 #1448
